---
all:
  children:
    k3s:
      children:
        k3sMasters:
          hosts:
            cubox:
              ansible_host: 192.168.178.88
              k3s_flannel_interface: eth0
              ansible_ssh_private_key_file: ~/.ssh/id_rsa
        k3sNodes:
          hosts:
            vagrantnode:
              ansible_host: 192.168.178.94
              ansible_ssh_user: vagrant
              ansible_ssh_private_key_file: /home/nolte/repos-ansible/schulung/qubox-k3s/local/x86Node/.vagrant/machines/k3snodeamd6401/virtualbox/private_key
              k3s_flannel_interface: eth1
            rpidisplay:
              ansible_host: 192.168.178.87
              ansible_ssh_private_key_file: ~/.ssh/id_rsa
              k3s_flannel_interface: wlan0
