---
_extends: gh-plumbing:.github/commons-settings.yml

repository:
  name: ansible-inventories
  description: Git Based Ansible Inventories Project
  homepage: ""
  topics: ansible, ansible-inventories

branches:
  - name: master
    protection:
      required_pull_request_reviews: null
      required_status_checks: null
      enforce_admins: true
      restrictions: null
  - name: develop
    protection:
      required_pull_request_reviews: null
      required_status_checks:
        strict: true
        contexts:
          - "static / Static CI Tests"
      restrictions: null
