
selinux_enabled: false
audit_rules_enabled: false

ansible_user: pi
ansible_ssh_user: pi
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

ansible_ssh_private_key_file: ~/.ssh/id_ed25519
k3s_flannel_interface: eth0

system_supporters:
  - "nolte"
  - "ansible"
  - "pi"

#firewalld_enabled: false
#firewalld_exists: true