---
all:
  children:
    rpidevices:
      hosts:
        rpidisplay:
        rpihifybarry:
        rpigipo:
        rpistorage:
    k3s:
      children:
        k3sMasters:
          hosts:
            rpistorage:
        k3s_agent:
          hosts:
            rpidisplay:
            rpihifybarry:
            rpigipo:
