---
all:
  children:
    managedServices:
      children:
        k3s:
          vars:
            k3s_become_for_all: true
            firewalld_enabled: false
            firewalld_exist: false
            k3s_use_docker: false
            k3s_control_workers: true
            k3s_no_traefik: true
            k3s_no_servicelb: true
            k3s_no_local_storage: true
          children:
            k3sPrimary:
              vars:
                k3s_write_kubeconfig_mode: 744
                k3s_control_node: true
            #k3sSecondery:
            #  k3s_control_node: false
